version: "2"

linters:
  default: standard
  enable:
    - gocritic
    - gosec
    - misspell
    - revive
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - linters:
          - errcheck
        text: "Error return value of `(.*\\.Close)`"
      - linters:
          - gosec
        text: "G(204|304)"
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - unnamedResult
      settings:
        hugeParam:
          sizeThreshold: 128
    revive:
      rules:
        - name: unexported-return
          disabled: true
